services:
  database:
    container_name: lpilogue-db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: dnwnswls2501
      MYSQL_DATABASE: lpilogue
      MYSQL_ROOT_HOST: "%"
      TZ: 'Asia/Seoul'
    ports:
        - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"


  spring-boot-app:
    container_name: lpilogue-be
    restart: on-failure
    image: hadoroke/lpilogue-be:latest
    ports:
        - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/lpilogue?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "dnwnswls2501"
    depends_on:
      - database










