services:
  spring-boot-app:
    container_name: lpilogue-be
#    restart: on-failure
    image: hadoroke/lpilogue-be:latest
    ports:
        - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://lpilogue-db.c5msg0qqmmcw.ap-northeast-2.rds.amazonaws.com:3306/lpilogue?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "dnwnswls2501"
  
  flask-app:
    container_name: lpilogue-rec
    image: hadoroke/lpilogue-rec:latest
    ports:
        - "5000:5000"
