name: CI Pipeline

on:
  push:
    branches: [ "main" ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # 현재 레포지토리 가져오기
    - name: Checkout repository
      uses: actions/checkout@v4

      # Java 17 환경 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

      # Gradle 실행 권한 부여
    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

      # Gradle Build 실행
    - name: Build with Gradle
      run: ./gradlew clean build -x test  # 테스트 제외하고 빌드

    - name: Login to Dockerhub   
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push the Docker image
      run: |
        TAG=$(date +%s)
        docker build -t $DOCKER_USERNAME/lpilogue-be:$TAG -t $DOCKER_USERNAME/lpilogue-be:latest .
        docker push $DOCKER_USERNAME/lpilogue-be:$TAG
        docker push $DOCKER_USERNAME/lpilogue-be:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      

