name: Docker Image CI

on:
  push:
    branches: [ "main" ]
 

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # 현재 레포지토리 가져오기
    
    - name: Login to Dockerhub   
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push the Docker image
      run: |
        TAG=$(date +%s)
        docker build -t $DOCKER_USERNAME/lpilogue-be:$TAG -t $DOCKER_USERNAME/lpilogue-be:latest .
        docker push $DOCKER_USERNAME/lpilogue-be:$TAG
        docker push $DOCKER_USERNAME/lpilogue-be:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      

