name: CD Pipeline

on:
  workflow_run:
    # CI Pipeline이 실행된 후 실행
    workflows: [ "CI Pipeline" ]
    types:
      - completed


jobs:
  deploy:

    # 리눅스 서버의 Runner에서 실행
    runs-on: self-hosted
    steps:

        # 현재 레포지토리 가져오기
        - name: Checkout repository
          uses: actions/checkout@v4

        # Docker 로그인
        - name: Login to Dockerhub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

        # Docker 이미지 Pull
        - name: Pull Docker image
          run: docker pull $DOCKER_USERNAME/lpilogue-be:latest
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

        # 기존에 실행중인 Docker 컨테이너 삭제
        - name: Stop and remove Docker container
          run: docker stop lpilogue-be && docker rm lpilogue-be || true

        # Docker 컨테이너 실행
        - name: Run Docker container
          run: docker run -d -p 8080:8080 --name lpilogue-be $DOCKER_USERNAME/lpilogue-be:latest
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}